# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: AB Site Pipeline

on:
  pull_request:
    branches: 
      - develop
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Installing NPM Scripts
      run: npm i
    - name: Run build
      run: npm run build --if-present
    - name: Deploy to Netlify
      run: curl -X POST -d '{}' ${{ secrets.NETLIFY_BUILD_HOOK }}

